name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  mri:
    strategy:
      matrix:
        ruby_version:
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
        gemfile:
          - gemfiles/rails_80.gemfile
          - gemfiles/rails_72.gemfile
          - gemfiles/rails_71.gemfile
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake test

  rails_edge:
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: gemfiles/rails_edge.gemfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - run: bundle exec rake test || echo "Rails edge test is done."

  ruby_edge:
    strategy:
      matrix:
        ruby_version:
          - 'ruby-head'
        gemfile:
          - gemfiles/rails_edge.gemfile
          - gemfiles/rails_80.gemfile
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake test || echo "Ruby edge test is done."
